In [2]:
import numpy as np

In [5]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [7]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.random.rand(1)

array([0.56402865])

In [23]:
mak = np.arange(11,26).reshape(3,5)
mak

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
mak[2:,:2]

array([[21, 22]])

In [32]:
import numpy as np

In [38]:
pap = np.arange(10,51)
pap

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [49]:
np.where(pap%2==0,pap,pap**2)

array([  10,  121,   12,  169,   14,  225,   16,  289,   18,  361,   20,
        441,   22,  529,   24,  625,   26,  729,   28,  841,   30,  961,
         32, 1089,   34, 1225,   36, 1369,   38, 1521,   40, 1681,   42,
       1849,   44, 2025,   46, 2209,   48, 2401,   50])

In [52]:
np.where(pap%2==0,pap,0)

array([10,  0, 12,  0, 14,  0, 16,  0, 18,  0, 20,  0, 22,  0, 24,  0, 26,
        0, 28,  0, 30,  0, 32,  0, 34,  0, 36,  0, 38,  0, 40,  0, 42,  0,
       44,  0, 46,  0, 48,  0, 50])

In [53]:
np.where(pap%2==1,pap,0)

array([ 0, 11,  0, 13,  0, 15,  0, 17,  0, 19,  0, 21,  0, 23,  0, 25,  0,
       27,  0, 29,  0, 31,  0, 33,  0, 35,  0, 37,  0, 39,  0, 41,  0, 43,
        0, 45,  0, 47,  0, 49,  0])