In [5]:
lit=[[1,2],[4,5]]
type(lit)

list

In [8]:
lit[0][1]

2

In [12]:
for x in lit:
   # print(x)
    for y in x:
        print(y)

1
2
4
5


In [16]:
# basics of numpy


In [17]:
import numpy as np

In [42]:
my_list = np.array([[1,2],[3,4],[5,7]], dtype=np.int64)
my_list

array([[1., 2.],
       [3., 4.],
       [5., 7.]], dtype=float32)

In [26]:
type(my_list)

numpy.ndarray

In [27]:
print("method 1 to show shape", np.shape(my_list))
print("method 2 to show shape", my_list.shape)

method 1 to show shape (3, 2)
method 2 to show shape (3, 2)


In [31]:
np.arange(start=2, stop=15, step=2)

array([ 2,  4,  6,  8, 10, 12, 14])

In [32]:
np.arange(5,25,5)

array([ 5, 10, 15, 20])

In [33]:
np.zeros(4)

array([0., 0., 0., 0.])

In [34]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [35]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [36]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [43]:
my_list.dtype


dtype('float32')

In [44]:
np.linspace(4,10,4)

array([ 4.,  6.,  8., 10.])

In [50]:
np.linspace(1,4,5)

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [67]:
np.random.randint(8,20,5)

array([ 9,  9, 12,  8, 12])

In [77]:
np.random.rand(6,2)

array([[0.07730542, 0.82337215],
       [0.49570693, 0.60058694],
       [0.33282581, 0.99650297],
       [0.98793025, 0.82368724],
       [0.01082988, 0.55646157],
       [0.80174091, 0.78940926]])

In [78]:
my_list

array([[1., 2.],
       [3., 4.],
       [5., 7.]], dtype=float32)

In [81]:
my_list.reshape(2,3).transpose()

array([[1., 4.],
       [2., 5.],
       [3., 7.]], dtype=float32)

In [89]:
np.arange(2,20,2).reshape(9,)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [92]:
np.linspace(2,15,6).reshape(3,2)

array([[ 2. ,  4.6],
       [ 7.2,  9.8],
       [12.4, 15. ]])

In [94]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])